package com.web.entity;
// Generated Apr 5, 2022 1:09:35 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Customers generated by hbm2java
 */
@Entity
@Table(name="customers"
    ,schema="dbo"
    ,catalog="webbanhang2"
)
public class Customer  implements java.io.Serializable {


     private int customerId;
     private String customerName;
     private Boolean gender;
     private Date dob;
     private String email;
     private String phone;
     private String status;
     private String password;
     private Date registeredDate;
     private Set<Cart> cartses = new HashSet<Cart>(0);

    public Customer() {
    }

	
    public Customer(int customerId, String customerName) {
        this.customerId = customerId;
        this.customerName = customerName;
    }
    public Customer(int customerId, String customerName, Boolean gender, Date dob, String email, String phone, String status, String password, Date registeredDate, Set<Cart> cartses) {
       this.customerId = customerId;
       this.customerName = customerName;
       this.gender = gender;
       this.dob = dob;
       this.email = email;
       this.phone = phone;
       this.status = status;
       this.password = password;
       this.registeredDate = registeredDate;
       this.cartses = cartses;
    }
   
     @Id 

    
    @Column(name="CustomerId", unique=true, nullable=false)
    public int getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }

    
    @Column(name="CustomerName", nullable=false)
    public String getCustomerName() {
        return this.customerName;
    }
    
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    
    @Column(name="Gender")
    public Boolean getGender() {
        return this.gender;
    }
    
    public void setGender(Boolean gender) {
        this.gender = gender;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DOB", length=10)
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }

    
    @Column(name="Email")
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="Phone", length=30)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="Status", length=20)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="Password", length=30)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RegisteredDate", length=10)
    public Date getRegisteredDate() {
        return this.registeredDate;
    }
    
    public void setRegisteredDate(Date registeredDate) {
        this.registeredDate = registeredDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="customers")
    public Set<Cart> getCartses() {
        return this.cartses;
    }
    
    public void setCartses(Set<Cart> cartses) {
        this.cartses = cartses;
    }




}


